### ISSUE TITLE
Nevalidní CN www.faktyoklime.sk

### ISSUE THREAD

**Issue by repli2dev** [faktaoklimatu/web-sk#2]
Přístup na faktyoklime.sk je ok, na www.faktyoklime.sk nikoliv: NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by mukrop** [comment]
To vieme, rovnaky problem je aj na ceskej verzii. Ale aktualne s tym neviem nic urobit, pretoze GitHub si vydava certifikat automatizovane a na www alt-name ho nejde presvedcit. Chvilu to vyzeralo, ze by sa to dalo riesit alternativnou konfiguraciou DNS, ale nevykoumal som to. Ak mas tip, ako na to, sem s nim :-).
Inak sa to asi vyriesi, ked zmigrujeme z Github pages na Google Firebase Hosting (dost o tom uvazujem).

**Comment by repli2dev** [comment]
Hmm: https://github.com/isaacs/github/issues/1675

**Comment by mukrop** [comment]
Je nachystana zmena deploy z GitHub pages na Google Firebase, takze tento problem sa vyriesi. Uz to funguje na https://factsonclimate.org/ a https://www.factsonclimate.org/
