### ISSUE TITLE
opravit chybu v grafice koncentrace CO2

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-sk#31]
Slovenská grafika https://faktyoklime.sk/infografiky/koncentracia-co2 obsahuje chybu zanesenou při pokusu o aktualizaci, ale bez diskuse významu - nejvyšší naměřené koncentrace na Mauna Loa nebyly 419ppm letos v únoru ale 417ppm minulý květen. Viz zdrojová data ze Scrippsova institutu... (to, že měření měly okolo 7. února krátkdobý výkyv není relevantní, protože zobrazujeme BACKGROUND concentrations - a když se podíváte na celý únor, vidíte pozadí okolo 416ppm)

Doplnění: letošní maximum okolo 420 ppm očekáváme v květnu...

**Comment by kikinna** [comment]
Tady opravená verze
https://github.com/faktaoklimatu/graphics/tree/main/data-visualization/climate-indicators/world/co2-concentration-in-800-000-years

**Comment by LenkaSedlackova** [comment]
v texte už je to opravené + doplnená info, že sa jedná o *priemernú mesačnú koncentráciu*, lebo to tam nikde nebolo doteraz uvedené - #32 . diky @kikinna za rýchlu úpravu IG :)

**Comment by ondraspribyla** [comment]
ad měsíční koncentrace: good point :-) (a teď když jsem napsal "měsíční"
začal jsem přemýšlet, jestli to někdo nemůže chápat jako koncentrace na
měsíci - začínám být paranoidní)

O.
