### ISSUE TITLE
Nahrať novú grafiku - opravenú

### ISSUE THREAD

**Issue by vrq-github** [faktaoklimatu/web-sk#59]
Kristi ma dnes upozornila, že som mala posunuté jedno číslo v tejto ig. Mohla by som proprosiť o update?
https://drive.google.com/file/d/1mCDJFAp0Afi41zoym4Glu_SPNmTE1Y-y/view?usp=sharing

**Comment by mukrop** [comment]
Nahrala si PNG export, ja by som potreovat PDF :-/.

**Comment by LenkaSedlackova** [comment]
@vrq-github ahoj, toto už je vyriešené, prosím?

**Comment by mukrop** [comment]
Myslim si, ze nie je (inak by som to bol zavrel). Ale jediny rozdiel, ktory vidim medzi linkovanou grafiou a tou publikovanou je inak formatovana legenda. Takze neviem, ci je toto issue este relevantne. @vrq-github?

**Comment by mukrop** [comment]
Triesti pozornost a nie je zasadna chyba. Zatvaram, budeme sa sustredit na veci s vyssim dopadom.
